name: Android CI (Espresso Tests)

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execution permission to gradlew
        run: chmod +x gradlew

      # ----------------------------------------------------
      #  FIXED EMULATOR CONFIG (ARM + HEADLESS + STABLE)
      # ----------------------------------------------------
      - name: Start AVD and Run Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: default
          arch: x86_64
          script: ./gradlew connectedDebugAndroidTest
          disable-animations: true
          emulator-options: |
            -no-snapshot
            -no-window
            -noaudio
            -gpu swiftshader_indirect
            -skin 1080x1920
            -camera-back none
            -camera-front none
            -accel off             
            script: ./gradlew connectedDebugAndroidTest
